title: Emily Zhao
url: "https://over-ez.gitbub.io"
baseurl: "/home/"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: no
footer_url: "https://github.com/ankitsultana"
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/home/"
 - name: "Resume"
   link: "resume.pdf"
 - name: "Contact"
   link: "contact"
